/**:
  ros__parameters:
    input_topic: "control/move_mit_joint_states"
    output_topic: "control/move_mit"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    compliance:
      joint1: {kp: 1.0, kd: 0.2, feedforward_torque: 0.0}
      joint2: {kp: 1.0, kd: 0.2, feedforward_torque: 0.0}
      joint3: {kp: 1.0, kd: 0.2, feedforward_torque: 0.0}
      joint4: {kp: 1.0, kd: 0.2, feedforward_torque: 0.0}
      joint5: {kp: 1.0, kd: 0.2, feedforward_torque: 0.0}
      joint6: {kp: 1.0, kd: 0.2, feedforward_torque: 0.0}
