<?xml version="1.0"?>
<package format="3">
  <name>dls2_piper_bridge</name>
  <version>0.0.0</version>
  <description>ROS2 Python package providing Piper HAL node</description>
  <maintainer email="giulioturrisi@example.com">Giulio Turrisi</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>python3-setuptools</buildtool_depend>

  <depend>rclpy</depend>
  <depend>dls2_interface</depend>
  <exec_depend>piper_sdk</exec_depend>

  <exec_depend>python3</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
